server:
  port: 8081
spring:
  application:
    name: system
  datasource:
    url: jdbc:mysql://111.229.53.45:3306/szmall?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis
  redis:
    database: 0
    host: 111.229.53.45
    port: 6379
    password: Wbqsphr.1114redis
    timeout: 5000
  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 6d7c1897-941e-4e72-b2ef-c70b74f3efea  #nacos控制台配置 可以进行资源隔离，比如dev和test不一样
        group: szmall   #资源隔离，不同分组之间的服务不能互相调用
        cluster-name: CD  #抽象出来的一个参数，可以实现自己负载均衡算法优先调用同名的服务。比如成都机房的服务优先调用成都机房的
        metadata:
          version: v1  #数据隔离相同版本之间才能互相调用
#jwt
sz:
  rsa:
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrjqKjgtFZqUiF9nOOwkZXXTKsRXnS0Y0BffUy2tjs2TgYd6sCS3AC1o6Fxf1oVJTppOSAhY1zhT3jNvIUfERGiyMqeGLGyzheTkrbM9XMpY/iu0y9FBWjnzMJg3zlmJug+R0FCcXzEVI0Jk6+SJoqK0K8SRiIWxzf++X3Y98tXwIDAQAB
    privateKey: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAKuOoqOC0VmpSIX2c47CRlddMqxFedLRjQF99TLa2OzZOBh3qwJLcALWjoXF/WhUlOmk5ICFjXOFPeM28hR8REaLIyp4YsbLOF5OStsz1cylj+K7TL0UFaOfMwmDfOWYm6D5HQUJxfMRUjQmTr5ImiorQrxJGIhbHN/75fdj3y1fAgMBAAECgYEAlEnOOxewbZftoB3O9O7obkuYqV/EVX3cLBX8A+E28EMyQbPulSUvxMRAnVDuIWg671ogSRcnlVrui5/Kz/o56HKd1h3ldOEfUH+au3n1p9JsUSEYS49rGWVTD07HZ1OYnvh4PLMPRSle01n6yyeEpvngaYhZ6lLyFxO2hYivkwECQQDvBsB/uPXeg+9xPeaqp6nOSGPy+6KTCaDsvCKospPDdIYCygFk26jEoe694hZ59p+MfLFdbKYS16Ad8dIN8EQvAkEAt71dOoSjYM9AVt81KAghk0Gx16On+O/Fc668w5871obc/aq8ApHlGqu7C+GD5Y+OPf6bWUWhgpoE8okgh+jt0QJBAL6f2eGCdsMw4UKkpVMwR6H15ZAg0rUFFsv19oYndOSKB14uEBKJg/zdT/MrXdWCtBdsUl85iPC5+j4nXugy140CQFAJiQboqFKPdTNiX8FkaVvADjwk6hKiP5y4zTlZr7MvZCyLpwJnkykfDYeLYO0qr4eJ1Rn6HvTJKsaLvUP2z0ECQQCxkel5zfrzIt4ePgAjwe0qtsexpiZBvnChNX2utzJ0NzKFYaJQEs4KThosGaZ1XqovtEHwAiKukp40ief1QOSh
  jwt:
    header: Authorization
    token-start-with: Bearer
    base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
    token-validity-in-seconds: 7200000
    online-key: online-token
    code-key: code-key
    expire: 300000
logging:
  level:
    com:
      shanzhen:
        system:
          dao: debug
